spring.application.name=agrova-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/agrova
spring.datasource.username=${AGROVA_DB_USERNAME:postgres}
spring.datasource.password=${AGROVA_DB_PASSWORD}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration